### ISSUE TITLE
Add Babel Fees support

### ISSUE THREAD

**Issue by capt-nemo429** [capt-nemo429/nautilus-wallet#46]
Add support to [EIP31](https://github.com/ergoplatform/eips/pull/54)

## Todo
 - [x] Add fee selector UI
 - [x] Transaction building
 - [x] Transaction review UI
 - [x] Consider mempool for Babel Box selection
